/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'SR2_pc.exe'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct vector3;
struct object_vt;

/* 402 */
struct object
{
  object_vt *vt;
  object *field_4;
  int field_8;
  object *field_C;
  object *field_10;
  vector3 position;
  int field_20;
  int field_24;
  int field_28;
  int field_2C;
  int field_30;
  int field_34;
  int field_38;
  int field_3C;
  int field_40;
  int loaded_index;
  unsigned __int16 chunk_index;
  int field_4C;
  int field_50;
  int field_54;
  int field_58;
  int field_5C;
  int field_60;
  int field_64;
  int field_68;
  int field_6C;
  int field_70;
  int field_74;
  int field_78;
  int field_7C;
  int flags;
  int field_84;
  int field_88;
  int field_8C;
  int field_90;
  int field_94;
  int field_98;
  int field_9C;
  int field_A0;
  int field_A4;
  int field_A8;
  int field_AC;
  char *field_B0;
  int field_B4;
  int field_B8;
  int field_BC;
  int field_C0;
  int field_C4;
  int field_C8;
  int field_CC;
  int field_D0;
  int field_D4;
  int field_D8;
  int field_DC;
  int field_E0;
  int field_E4;
  int field_E8;
  int field_EC;
  int field_F0;
  int field_F4;
  int field_F8;
  int field_FC;
  int field_100;
  int field_104;
  int field_108;
  int field_10C;
  int field_110;
  int field_114;
  int field_118;
  int field_11C;
  int field_120;
  int field_124;
  int field_128;
  int field_12C;
  int field_130;
  int field_134;
  int field_138;
  int field_13C;
  int field_140;
  int field_144;
  int field_148;
  int field_14C;
  int field_150;
  int field_154;
  int field_158;
  int field_15C;
  int field_160;
  int field_164;
  int field_168;
  int field_16C;
  int field_170;
  int field_174;
  int field_178;
  int field_17C;
  int field_180;
  int field_184;
  int field_188;
  int field_18C;
  int field_190;
};

/* 401 */
struct object_vt
{
  float *(__thiscall *func_00)(object *this, float *a2, int a3);
  int (__thiscall *func_01)(object *this);
  float *(__thiscall *func_02)(object *this, float *a2, float *a3);
  float *(__thiscall *func_03)(object *this, float *a2, float *a3);
  char (__thiscall *func_04)(object *this, char a2);
  void (__thiscall *func_05)(object *this);
  int (__thiscall *func_06)(object *this, char a2, char a3);
  int (__thiscall *func_07)(object *this, int a2, int a3);
  __int16 (__thiscall *func_08)(object *this);
};

/* 339 */
struct vector3
{
  float x;
  float y;
  float z;
};

