/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'SR2_pc.exe'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct vhashtable_template_vt;

/* 398 */
struct vhashtable_template
{
  vhashtable_template_vt *vt;
  int table_max_size;
  unsigned __int16 *data_sparse_array;
  int table_num_elements;
  int max_num_elements;
};

/* 397 */
struct vhashtable_template_vt
{
  int (__thiscall *dtor)(vhashtable_template *__hidden this, int flags$);
  int (__thiscall *create)(vhashtable_template *__hidden this, int, int, int, int);
  bool (__thiscall *add)(vhashtable_template *__hidden this, int, _WORD *, int);
  bool (__thiscall *find)(vhashtable_template *__hidden this, unsigned __int16 *index_out, int, int);
  bool (__thiscall *remove)(vhashtable_template *__hidden this, int, _WORD *);
  void (__thiscall *reset)(vhashtable_template *__hidden this);
  void (__thiscall *clear)(vhashtable_template *__hidden this);
};

